# Generated by Django 4.2.2 on 2023-06-28 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(default='Личное', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='myapp.category', verbose_name='Категория'),
        ),
    ]
