# Generated by Django 4.2.2 on 2023-07-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['completed', models.Case(models.When(priority='высокий', then=0), models.When(priority='средний', then=1), models.When(priority='низкий', then=2), default=3, output_field=models.IntegerField())], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('высокий', 'Высокий'), ('средний', 'Средний'), ('низкий', 'Низкий')], default='средний', max_length=20, verbose_name='Приоритет'),
        ),
    ]
