# Generated by Django 4.2.2 on 2023-07-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['completed', models.Case(models.When(priority='высокий', then=0), models.When(priority='средний', then=1), models.When(priority='низкий', then=2)), 'due_date'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
